### ISSUE TITLE
README.md not informative

### ISSUE THREAD

**Issue by ligon** [harcourt-rebecca/eep153-proj4#1]
Possible to add information to README.md giving guidance about what files are used to conduct project analysis?  Perhaps using a markdown link to said file?

**Comment by ligon** [comment]
What is markdown?  Not clear.

**Comment by jnuesca** [comment]
Hi, here is a link to a document with guidance to using this repository: [https://docs.google.com/document/d/1axeQE59q7xzmWjjw1biYJoxv_EyFVNwoIqkZpNPVlqs/edit?usp=sharing](url)

**Comment by ligon** [comment]
Great!  Can you embed this information in README.md for easier access, or is that asking too much?

**Comment by jnuesca** [comment]
Should be fixed now, thanks for the comment!
