### ISSUE TITLE
Comment Double Spacing

### ISSUE THREAD

**Issue by glowang** [harcourt-rebecca/eep153-proj4#3]
Input #25 has double spaced comment. Should be single spaced 👍

**Comment by julie-tran** [comment]
Unclear- can you post a screenshot of the issue please?

**Comment by glowang** [comment]
![image](https://user-images.githubusercontent.com/38899812/57048020-53fb1900-6c27-11e9-9882-17d25769b9ce.png)

**Comment by glowang** [comment]
Might have been just a display error tho! @julie-tran

**Comment by jnuesca** [comment]
Updated file is being uploaded shortly, thanks for pointing this out!
