### ISSUE TITLE
File not found in the directory

### ISSUE THREAD

**Issue by aliraza1997** [harcourt-rebecca/eep153-proj4#5]
<img width="740" alt="Screen Shot 2019-05-01 at 3 45 00 PM" src="https://user-images.githubusercontent.com/47613819/57048096-902e7980-6c27-11e9-841f-7996911199e7.png">

**Comment by jnuesca** [comment]
Hi aliraza1997,

Do you have tanzanian_nps.ds downloaded? We left a comment for you at the top of the code block with instructions to change FILE_LOCATION to the specific directory where this file lives. It will look different for each user depending on where the file lives.
